### PR TITLE
Update wifi-ssid 

### PR DESCRIPTION
**Pull request by mrkeshav-05**
# wifi-ssid file is completed

### CODE REVIEW

**Comment by ecxtacy** [comment]
Hi @mrkeshav-05, thanks for contributing here. You should write a proper PR description clearly describing the changes. Also format the PR properly.

**Comment by mrkeshav-05** [comment]
This PR introduces a script to extract the WiFi username (SSID) of the currently connected network on a laptop or PC. The script utilizes the iw dev wlan0 link command output to fetch the SSID information.

Changes Made
Added a script to extract the WiFi SSID.
Utilized the iw dev wlan0 link command to retrieve SSID information.
Implemented parsing logic to extract the SSID from the command output.


This PR aims to enhance the functionality of the project by providing a convenient method to extract the WiFi SSID from the currently connected network. Your review and feedback are highly appreciated.

Thank you!

**Comment by rootCircle** [comment]
Hi @mrkeshav-05, congrats on your first PR to this repo! It is generally a good practice that you put that in description itself! (Notice the edit button)

Also, there should be only one issue solved by a single PR, your PR seem to include codes for other issues as well, please remove that, make use of `branches` to cleanly perform that.

I have tested your code and it works, that's great! :smile:

**Comment by rootCircle** [comment]
ping me here when you're done with those, so we can move forward with your PR!

**Comment by ecxtacy** [comment]
Kindly use separate branches for different PRs, you can make a new PR for this with a new branch. Closing this.

**Pull request closed without merging**
