### PR TITLE
#4 script to remove binary files

### PR DESCRIPTION
**Pull request by Sidharth-Singh10**
In this PR I wrote a script to remove binary files ( .bin ).
I used 'fd' command is a which more modern and efficient alternative to 'find' command.
'-e' flag searches for '.bin' extension in current directory and sub directory
'-x' flag runs commands (here 'rm' )  for each search.

### CODE REVIEW

**Comment by rootCircle** [comment]
Hi @Sidharth-Singh10, there is a issue in your implementation, your code checks for file extension for checking binaries, but most of the binary in linux don't actually have an extension. (See `/usr/bin/` for example)

Please try fixing that (hint: ELF)

ping me here when you're done with those, so we can move forward with your PR!

**Comment by Sidharth-Singh10** [comment]
@rootCircle 
Updated the logic to delete binary files.
`find . -type f -exec file {}` Finds all files in current directory and sub directory and determines their file type
`grep ELF` Filters elf file type
`cut -d: -f1` extracts the file path which is used as input to `rm`
'rm -f' deletes the filtered executable files

**Comment by rootCircle** [comment]
LGTM :+1: Awesome work @Sidharth-Singh10! 

Cool thing, you can use this to delete those binaries of C,C++ you made during development etc!

Great by the way, Accepted

**Comment by rootCircle** [comment]
fixes #4

**Pull request closed without merging**
