### PR TITLE
#3 :adding feature rm-gitignore

### PR DESCRIPTION
**Pull request by piyushkumar079**
#3 : Clean Ignored Files in Git Repos
This script removes ignored files from Git repositories using git clean -Xdf.
Added Comments in code to explain the same
image

### CODE REVIEW

**Comment by rootCircle** [comment]
hi @piyushkumar079, clean implementation! can you briefly explain what your code does?

**Comment by rootCircle** [comment]
also, you can print a helpful message if current working directory is not a git directory rather than `Finished cleaning ignored files in Git repositories.`

**Comment by rootCircle** [comment]
ping me here when you're done with those, so we can move forward with your PR!

**Comment by piyushkumar079** [comment]
> ping me here when you're done with those, so we can move forward with your PR!

@rootCircle 
explanation
`git_repos=$(find . -name .git -type d -prune)`
this line finds the ./git folder 
`cd ..`
this is done since .gitignore file lives outside of ./git folder
`git clean -Xdf`
with -Xdf flag this line forcefull deletes the files mentioned inside the .gitignore file
`cd -` 
this takes us back to the previous directory (like in back in a browser)
`>/dev/null 2>&1`
this is a popular method that supresses error messages 

Changes
made the recommeded change

**Comment by rootCircle** [comment]
> explanation
git_repos=$(find . -name .git -type d -prune)
this line finds the ./git folder

In the comment in code you wrote and I quote `# Loop through each Git repository`, what do you mean by that, there can be one and only more .git in CWD or am I mistaken somewhere?

**Comment by rootCircle** [comment]
> Changes
made the recommeded change

LGTM :+1:

**Comment by piyushkumar079** [comment]
> > explanation
> > git_repos=$(find . -name .git -type d -prune)
> > this line finds the ./git folder
> 
> In the comment in code you wrote and I quote `# Loop through each Git repository`, what do you mean by that, there can be one and only more .git in CWD or am I mistaken somewhere?

yes as quoted from the moderator
_To find list of all git repos inside current directory you can use: "find . -name .git -type d -prune"_
it starts searching from the current directory (represented by the dot, ".") and descends into all subdirectories.
a example would be if a project has both frontend and backend in a single directory and both the directories are tracked by git independently. and if the script is run on the root of both the directories it will actually find both the .git directory and then clean .gitignore by looping thru each repo

**Comment by rootCircle** [comment]
> To find list of all git repos inside current directory you can use: "find . -name .git -type d -prune"
it starts searching from the current directory (represented by the dot, ".") and descends into all subdirectories.
a example would be if a project has both frontend and backend in a single directory and both the directories are tracked by git independently. and if the script is run on the root of both the directories it will actually find both the .git directory and then clean .gitignore by looping thru each repo

great explanation @piyushkumar079! LGTM, accepted

**Pull request closed without merging**
