### PR TITLE
prints permission in octal format #6

### PR DESCRIPTION
**Pull request by AMANVISHWAKARMA27**
Fixes #6 
image

### CODE REVIEW

**Comment by rootCircle** [comment]
hi @AMANVISHWAKARMA27, thanks for contribution!

few things, please include function usage in the code itself, include screenshot in PR description as well!

**Comment by rootCircle** [comment]
ping me here when you're done with those/need any help, so we can move forward with your PR!

**Comment by AMANVISHWAKARMA27** [comment]
> hi @AMANVISHWAKARMA27, thanks for contribution!
> 
> few things, please include function usage in the code itself, include screenshot in PR description as well!

@rootCircle, if u could explain me a bit more detail what I have to do ?

**Comment by rootCircle** [comment]
> @rootCircle, if u could explain me in a bit more detail what I have to do ?

currently you have the function, but we are not using up to satisfy the issue description!

simply put, issue description requires something like this given below, but your code does doesn't provide the usage

```bash
> perms README.md
642 README.md
```

**Comment by AMANVISHWAKARMA27** [comment]
> > @rootCircle, if u could explain me in a bit more detail what I have to do ?
> 
> currently you have the function, but we are not using up to satisfy the issue description!
> 
> simply put, issue description requires something like this given below, but your code does doesn't provide the usage
> 
> ```shell
> > perms README.md
> 642 README.md
> ```

Ahh got it. Doing it asap.

**Comment by AMANVISHWAKARMA27** [comment]
@rootCircle , it is done now as per your suggestion.
Screenshot 2024-03-17 105932

**Comment by rootCircle** [comment]
LGTM :+1: Accepted!

**Pull request closed without merging**
