### PR TITLE
added code for cpu temperature

### PR DESCRIPTION
**Pull request by AMANVISHWAKARMA27**
fixes #8 

image

### CODE REVIEW

**Comment by rootCircle** [comment]
your pr still doesn't solves the issues as stated in #8. The values are presumably in mill-celcius and mill-farhenheit.

image

please fix that! also write good pr description and include screenshot of your code running/ not your code (we can see the changes in the _File changes_ tab above)

ping me here when you're done with those/need any help, so we can move forward with your PR!

**Comment by AMANVISHWAKARMA27** [comment]
@rootCircle  please review the code again.
Also I encountered a problem that the code was not problem properly so I ran it on my friends system which is Linux. There it ran correctly. 
WhatsApp Image 2024-03-17 at 10 17 43_cceb653c

**Comment by rootCircle** [comment]
>  Also I encountered a problem that the code was not problem properly so I ran it on my friends system which is Linux. There it ran correctly.

Hey! @AMANVISHWAKARMA27, actually currently your implementation truncates the decimal place values, can you come up with something that includes that too in your code

So, 
Temperature in Celsius: 48.2 C
Instead of
Temperature in Celsius: 48 C

**Comment by AMANVISHWAKARMA27** [comment]
> > Also I encountered a problem that the code was not problem properly so I ran it on my friends system which is Linux. There it ran correctly.
> 
> Hey! @AMANVISHWAKARMA27, actually currently your implementation truncates the decimal place values, can you come up with something that includes that too in your code
> 
> So, Temperature in Celsius: 48.2 C Instead of Temperature in Celsius: 48 C

Yess I can try.

**Comment by rootCircle** [comment]
ping me here when you're done with those/need any help, so we can move forward with your PR!

**Comment by AMANVISHWAKARMA27** [comment]
@rootCircle , it is fine now. 
Giving output upto two decimal places.
WhatsApp Image 2024-03-17 at 10 29 49_921bbf19

**Comment by rootCircle** [comment]
LGTM :+1: Accepted Thanks for your contribution!

**Pull request closed without merging**
