### PR TITLE
#7 added more special cases

### PR DESCRIPTION
**Pull request by Sidharth-Singh10**
This pull request updates the script by adding more special cases of file types to group them into custom folders.
Changes:
1.  Added support for special cases to group specific file types into custom folders.
2.  Updated the special_cases array with additional patterns and folder names.

### CODE REVIEW

**Comment by rootCircle** [comment]
Hi @Sidharth-Singh10, congo on the second one! Can you check and fix these warnings? Confirm if you're not getting these warnings? 

image

**Comment by rootCircle** [comment]
Few points
- Please add fixes #n in the PR description not in title
- Add screenshot/video(if required) in PR description as well
- Write proper commit message, even if they seem relevant to you, it might look odd in commit history if merged!

**Comment by rootCircle** [comment]
ping me here when you're done with those, so we can move forward with your PR!

**Comment by rootCircle** [comment]
>  The warning occurs due to the use of "egrep" which is now considered outdated, "grep -E" is now the better alternative to it. Since "egrep" is used in the source code, I did not update the "egrep" to "grep -E" as the issue was to add more special cases.

You can update usage of `egrep` to `grep -E` in this script only! Use the same PR, need not to create a new PR for it!

Ping me when that's done!

**Comment by Sidharth-Singh10** [comment]
@rootCircle 
1.Fixed the warning occuring due the use of `egrep`
2. Fixed the warning occuring due use of `^*`  in regex

**Comment by rootCircle** [comment]
> 1.Fixed the warning occuring due the use of egrep
2. Fixed the warning occuring due use of ^* in regex

Looks really great now! Good job @Sidharth-Singh10, accepted!

**Comment by rootCircle** [comment]
fixes #7

**Pull request closed without merging**
