### PR TITLE
Removes all files written in .gitignore of any git repo

### PR DESCRIPTION
**Pull request by shuklamaneesh23**
Solved issue #3 ,

This pull request enhances the existing Gitignore cleanup script to improve efficiency and usability. The script now accurately removes files specified in the `.gitignore` files of Git repositories found within the current directory and its subdirectories.

Please review and merge at your earliest convenience.

### CODE REVIEW

**Comment by rootCircle** [comment]
> Please review and merge at your earliest convenience.

Please avoid adding sense of urgency in your PR unless solving a critical bug, doing this unnecessary bogs down the maintainers

**Comment by rootCircle** [comment]
I am getting error running your script, ensure proper testing before making a PR!

image

ping me here when you're done with those/need any help, so we can move forward with your PR!

**Comment by shuklamaneesh23** [comment]
@rootCircle ,I have fixed the issue and tested it successfully.Please review it.
Screenshot 2024-03-17 at 11 20 29 AM

**Comment by rootCircle** [comment]
LGTM :+1: Accepted!

**Pull request closed without merging**
