### PR TITLE
Added rm-gitignore script #3

### PR DESCRIPTION
**Pull request by Priyanshu-2005**
issue #3 
**Added the entire functional script with comments to improve readablity.**
The script would first check all the files in .gitignore file and move to the corresponding location accordingly and then delete that file mentioned in .gitignore file.
 
The output can be seen in the images:

_Files mentioned in .gitignore file_
**Command Used:**
`cat .gitignore`
Screenshot from 2024-03-15 11-29-05

_Before running the script_
**Command Used:**
`tree`
Screenshot from 2024-03-15 11-26-58

_After running the script_
**Commands Used:**
`bash rm-gitignore`
`tree`
Screenshot from 2024-03-15 11-27-53

as we can see index2.js and index.js present in src2 folder got deleted

Kindly look into this

### CODE REVIEW

**Comment by rootCircle** [comment]
>  Added the entire functional script with comments to improve readablity.

Please use AI with sanity!

**Comment by rootCircle** [comment]
please remove scripts/color and .gitignore file from the PR and can you explain your approach please!

**Comment by Priyanshu-2005** [comment]
@rootCircle Sure here is the explanation for the code

**Explanation of the code**
`find . -type f -name .gitignore | while read -r gitignore; `
To search for all .gitignore files. and pipe them to the while loop which iterates over them one by one

`cd "$(dirname "$gitignore")" || continue`
To change the directory accordingly mentioned in the .gitignore file
example)
If .gitignore files contains `src/index` file then it would route to that folder src

`echo "Removing files listed in .gitignore for directory: $(pwd)"`
Prints the message and mentions the present working directory

`while IFS= read -r pattern; do`
Starts reading the file line by line -r option prevents confusion of `/` with escape characters

`if [[ ! "$pattern" =~ ^(\s*#|\s*$) ]]; then`
It helps to skip the comments line and blank lines. It uses regular expression to do so

`rm -rf -- $pattern` 
Removes the file

`done < "$gitignore`
done implies that while loop has been finished `<` is basically a redirectional operator that allows us to take input from the file.

**Comment by rootCircle** [comment]
Your explanation looks great!

Also, @Priyanshu-2005 actually you didn't have to delete the color script just restore it to status quo! See the files changes section, the upstream (the main repo) has color script, but you deleted them! Trying fixing that if you can

ping me here when you're done with those/need any help, so we can move forward with your PR!

**Comment by rootCircle** [comment]
> Explanation of the code
find . -type f -name .gitignore | while read -r gitignore; 
To search for all .gitignore files. and pipe them to the while loop which iterates over them one by one

Why do you think that there might be multiple .gitignore in one CWD? Any specific purpose/motive?

**Comment by Priyanshu-2005** [comment]
@rootCircle I have restored it by adding the color file but now it is showing an empty file. Is it okay?

> Your explanation looks great!
> 
> Also, @Priyanshu-2005 actually you didn't have to delete the color script just restore it to status quo! See the files changes section, the upstream (the main repo) has color script, but you deleted them! Trying fixing that if you can
> 
> ping me here when you're done with those/need any help, so we can move forward with your PR!

**Comment by Priyanshu-2005** [comment]
There might be multiple .gitignore files present in subdirectories too (if they had been there) 
The find command will check all the subdirectories

**Comment by rootCircle** [comment]
> @rootCircle I have restored it by adding the color file but now it is showing an empty file. Is it okay?

Sorry, it doesn't! You can take help from https://www.freecodecamp.org/news/git-revert-file-reverting-a-file-to-a-previous-commit/

Simply, you need to restore the file using `git checkout <commit-hash-before-the-changes(first commit hash)> -- scripts/color`

**Comment by rootCircle** [comment]
> There might be multiple .gitignore files present in subdirectories too (if they had been there) .
The find command will check all the subdirectories

oh, that's cool.

**Comment by rootCircle** [comment]
ping me here when you're done with those/need any help, so we can move forward with your PR!

**Comment by Priyanshu-2005** [comment]
@rootCircle Changes made. Kindly look into this.

**Comment by rootCircle** [comment]
> @rootCircle Changes made. Kindly look into this.

LGTM :+1: Accepted! Thanks for your contribution!

**Pull request closed without merging**
