### PR TITLE
#2 Added weather Script

### PR DESCRIPTION
**Pull request by aryamagarwal**
Fixes #2
I have written a bash script to read the location given by the user and convert that into required format before fetching result from wttr.in.

weather

### CODE REVIEW

**Comment by aryamagarwal** [comment]
@rootCircle I have removed curl load text using curl -s and improved the overall script using shellcheck. Kindly review it.

**Comment by rootCircle** [comment]
LGTM :+1: Please move the file to `scripts/` directory! Ping when when it's done!

**Comment by aryamagarwal** [comment]
@rootCircle I have made the changes. Kindly review it.

**Comment by aryamagarwal** [comment]
@rootCircle I have shifted weather script in scripts folder.

**Comment by ecxtacy** [comment]
Looks good. Nice work.

**Pull request closed without merging**
