### PR TITLE
#9 added more colors

### PR DESCRIPTION
**Pull request by Sidharth-Singh10**
Added more bash colors
reference : https://gkarthiks.github.io/quick-commands-cheat-sheet/bash_command.html

### CODE REVIEW

**Comment by umeshSinghVerma** [comment]
Hii @Sidharth-Singh10  kindly create a new branch for your feature and also improve PR message

**Comment by rootCircle** [comment]
Congrats on your first contribution to this repo!
Just a FYI!
@Sidharth-Singh10 please don't solve two issues in one single PR! remember one issue per PR!

please move cpu-temperature script to another PRs and remove it from here! Ping me when it's done!

**Comment by rootCircle** [comment]
fixes #9

**Comment by ecxtacy** [comment]
Kindly associate relevant commits with this PR. Closing this since irrelevant commits have been pushed. You can create a new PR with the relevant commit.

**Pull request closed without merging**
