### PR TITLE
Write rm-gitignore script. #3

### PR DESCRIPTION
**Pull request by rishyym0927**
This pull request #3 addresses the issue [#3], which involves creating a script to remove all files specified in the .gitignore files located at the root of each Git repository found within the current directory.

Changes Made:

Created a Bash script named `rm-gitignore` to automate the process.
Utilized the find command to locate all Git repositories within the current directory.
Implemented a loop to iterate over each repository and navigate to its root directory.
Checked for the existence of a .gitignore file in each directory.
If a .gitignore file was found, read its contents and used the find command to remove files specified in it.
Displayed appropriate messages to indicate the progress and status of the script execution.

### CODE REVIEW

**Comment by rootCircle** [comment]
Updated your PR description, please check confirm in your PR description, before!


Your code works fine, but in output, instead of showing the files deleted, it is only showing the parent directory!

image

**Comment by rootCircle** [comment]
ping me here when you're done with those/need any help, so we can move forward with your PR!

**Comment by ecxtacy** [comment]
Also write proper commit messages @rishyym0927. Commit message heading should convey briefly what the commit does.

**Comment by rootCircle** [comment]
closed due to inactivity! since the author provided the basic working prototype based on the issue, marks will be provided based on that!

**Pull request closed without merging**
