### PR TITLE
#8 CPU die temperature in Celsius and Fahrenheit

### PR DESCRIPTION
**Pull request by Prudhvi-232**

### CODE REVIEW

**Comment by Prudhvi-232** [comment]
Fixes #8 

1.Extract the CPU die temperature in milli-Celsius from the system files.
2.Convert the milli-Celsius temperature to Celsius.
3.Convert the Celsius temperature to Fahrenheit and output both temperatures in the desired format.
4.It outputs the current CPU die temperature in milli-degree Celsius, converts it to Celsius and Fahrenheit, and displays the temperatures.

**Comment by rootCircle** [comment]
@umeshSinghVerma can you confirm if it works fine on Ubuntu or other debian based distros?

**Comment by rootCircle** [comment]
@Prudhvi-232 can you send a working screenshot of this?

> @umeshSinghVerma can you confirm if it works fine on Ubuntu or other debian based distros?

cc @ecxtacy

**Comment by ecxtacy** [comment]
Works on most, but its slightly hardware dependent, but ig that shouldn't be a barrier.

**Comment by ecxtacy** [comment]
You should write a proper PR description and any photo if there are visual changes.

**Pull request closed without merging**
