### PR TITLE
#8 formatted the output of cpu-temperature script

### PR DESCRIPTION
**Pull request by Sidharth-Singh10**
This pull request updates the output format of temperature values from milli-celsius to Celsius and Fahrenheit. 
With this change, the temperature values are converted to Celsius and Fahrenheit, providing a more intuitive and user-friendly output format.

Changes Made:
1.   Updated the conversion logic to calculate temperature values in Celsius and Fahrenheit.
2.   Updated the output format to display temperature values in Celsius and Fahrenheit.

### CODE REVIEW

**Comment by ecxtacy** [comment]
Hi @Sidharth-Singh10, thanks for putting up the PR.
It's a good practice to use proper capitalisation in the PR heading and also try to include screenshots of the output.

**Comment by ecxtacy** [comment]
No need of mentioning #8 in the PR heading, rather include a `Fixes #issue_number` in the PR description.

**Comment by rootCircle** [comment]
Hi @Sidharth-Singh10, congrats on your first contribution to this repo!

Please try to add screenshots/video while making a PR as a good practice!

Code works great! LGTM

**Comment by rootCircle** [comment]
fixes #8 
accepted :tada:

**Pull request closed without merging**
